kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test
  name: pod-deploy-stat
rules:
- apiGroups: ["", "apps"] # the core API group(pods) and apps(deployment)
  resources: ["pods"]
  verbs: ["get", "watch", "list", "update", "delete"]
