kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-deploy-stat-bind
  namespace: test
subjects:
- kind: User
  name: pyn
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-deploy-stat
  apiGroup: rbac.authorization.k8s.io